<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MB-W-VIGNESHWARAN" failures="0" tests="4" name="com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test" time="5.478" errors="0" timestamp="2022-09-13T22:29:38 IST" skipped="0">
  <testcase classname="com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test" name="Post_Send_OTP" time="0.875"/>
  <system-out/>
  <testcase classname="com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test" name="Post_Call_Connect_Invalid_Number" time="0.587"/>
  <system-out/>
  <testcase classname="com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test" name="Post_verify_OTP_with_Invalid_OTP" time="0.246"/>
  <system-out/>
  <testcase classname="com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test" name="Post_Call_Connect" time="3.770"/>
  <system-out/>
</testsuite> <!-- com.qa.medibuddy.Phlebo.api.test.Phlebo_OTP_Test -->
